Updated compiler tools.

diff --git a/cc-compile-dl b/cc-compile-dl
--- a/cc-compile-dl
+++ b/cc-compile-dl
@@ -1,16 +1,32 @@
 #!/bin/sh
 
+fatal()
+{
+  echo "cc-compile-dl: fatal: $1" 1>&2
+  exit 1
+}
+
 if [ $# -lt 1 ]
 then
-  echo "usage: source" 1>&2
+  echo "cc-compile-dl: usage: [@dir] source" 1>&2
   exit 1
 fi
 
-CC_DLFLAG=`head -n 1 conf-dlflag`
+#
+# check if new base dir was specified
+#
+
+BASE_DIR="."
+if [ $# -eq 2 ]
+then
+  BASE_DIR=`echo "$1" | sed 's/^@//g'`
+  shift
+fi
+
+CC_DLFLAG=`head -n 1 "${BASE_DIR}/conf-dlflag"`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-dlflag" 1>&2
-  exit 1
+  fatal "could not read ${BASE_DIR}/conf-dlflag"
 fi
 
-exec ./cc-compile $1 ${CC_DLFLAG}
+exec "${BASE_DIR}/cc-compile" $1 ${CC_DLFLAG}
diff --git a/cc-dlib b/cc-dlib
--- a/cc-dlib
+++ b/cc-dlib
@@ -2,33 +2,41 @@
 
 if [ $# -lt 2 ]
 then
-  echo "usage: basename objects ..." 1>&2
+  echo "cc-dlib: usage: [@dir] basename objects ..." 1>&2
   exit 1
 fi
 
-LD_TYPE=`head -n 1 conf-ldtype`
-if [ $? -ne 0 ]
+#
+# check if new base dir was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
 then
-  echo "fatal: could not read conf-ldtype" 1>&2
-  exit 1
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
 fi
-LD=`head -n 1 conf-ld`
+
+LD_TYPE=`head -n 1 ${BASE_DIR}/conf-ldtype`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-ld" 1>&2
-  exit 1
+  fatal "could not read ${BASE_DIR}/conf-ldtype"
 fi
-SYS_TYPE=`head -n 1 conf-systype`
+LD=`head -n 1 ${BASE_DIR}/conf-ld`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-systype" 1>&2
-  exit 1
+  fatal "could not read ${BASE_DIR}/conf-ld"
 fi
-SO_SUFFIX=`head -n 1 conf-sosuffix`
+SYS_TYPE=`head -n 1 ${BASE_DIR}/conf-systype`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-sosuffix" 1>&2
-  exit 1
+  fatal "could not read ${BASE_DIR}/conf-systype"
+fi
+SO_SUFFIX=`head -n 1 ${BASE_DIR}/conf-sosuffix`
+if [ $? -ne 0 ]
+then
+  fatal "could not read ${BASE_DIR}/conf-sosuffix"
 fi
 
 main="$1"
@@ -49,8 +57,7 @@ fi
 libname=`./mk-libname "${main}"`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not execute ./mk-libname" 1>&2
-  exit 1
+  fatal "could not execute ./mk-libname"
 fi
 
 # major version number
@@ -59,8 +66,7 @@ then
   VMJ=`head -n 1 ${main}.vmj 2>/dev/null`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read ${main}.vmj" 1>&2
-    exit 1
+    fatal "could not read ${main}.vmj"
   fi
 fi
 
@@ -70,8 +76,7 @@ then
   VMN=`head -n 1 ${main}.vmn 2>/dev/null`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read ${main}.vmn" 1>&2
-    exit 1
+    fatal "could not read ${main}.vmn"
   fi
 fi
 
@@ -136,8 +141,7 @@ case "${LD_TYPE}" in
     ${LD} -shared -soname "${libname}" -o "${libname}" ${1+"$@"} ${LDFLAGS}
     ;;
   *)
-    echo "fatal: unknown compiler - cannot produce shared objects" 1>&2
-    exit 1
+    fatal "unknown compiler - cannot produce shared objects"
     ;;
 esac
 
diff --git a/mk-dlflag b/mk-dlflag
--- a/mk-dlflag
+++ b/mk-dlflag
@@ -1,36 +1,49 @@
 #!/bin/sh
 
+fatal()
+{
+  echo "mk-dlflag: fatal: $1" 1>&2
+  exit 1
+}
+
+#
+# check if new base dir was specified
+#
+
+BASE_DIR="."
+if [ $# -eq 2 ]
+then
+  BASE_DIR=`echo "$1" | sed 's/^@//g'`
+  shift
+fi
+
 #
 # Print additional compiler flags necessary to compile object files that
 # can be used for shared libraries.
 #
 
-if [ -f conf-x-cctype ]
+if [ -f "${BASE_DIR}/conf-x-cctype" ]
 then
-  CC_TYPE=`head -n 1 conf-x-cctype`
+  CC_TYPE=`head -n 1 ${BASE_DIR}/conf-x-cctype`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-x-cctype" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-x-cctype"
   fi
-  SYS_TYPE=`head -n 1 conf-x-systype`
+  SYS_TYPE=`head -n 1 ${BASE_DIR}/conf-x-systype`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-x-systype" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-x-systype"
   fi
 else
-  CC_TYPE=`head -n 1 conf-cctype`
+  CC_TYPE=`head -n 1 ${BASE_DIR}/conf-cctype`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-cctype" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-cctype"
   fi
-  SYS_TYPE=`head -n 1 conf-systype`
+  SYS_TYPE=`head -n 1 ${BASE_DIR}/conf-systype`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-systype" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-systype"
   fi
 fi
 
@@ -64,7 +77,6 @@ case "${CC_TYPE}" in
     echo '-KPIC'
     ;;
   *)
-    echo 'fatal: unknown compiler - cannot print dynamic library flags' 1>&2
-    exit 1
+    fatal 'unknown compiler - cannot print dynamic library flags'
     ;;
 esac
diff --git a/mk-libname b/mk-libname
--- a/mk-libname
+++ b/mk-libname
@@ -1,23 +1,38 @@
 #!/bin/sh
-# $Id$
+
+fatal()
+{
+  echo "mk-libname: fatal: $1" 1>&2
+  exit 1
+}
 
 if [ $# -lt 1 ]
 then
-  echo "usage: basename" 1>&2
+  echo "mk-libname: usage: basename" 1>&2
   exit 1
 fi
 
-SYS_TYPE=`head -n 1 conf-systype`
-if [ $? -ne 0 ]
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
 then
-  echo "fatal: could not read conf-systype" 1>&2
-  exit 1
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
 fi
-SO_SUFFIX=`head -n 1 conf-sosuffix`
+
+SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-sosuffix" 1>&2
-  exit 1
+  fatal "could not read ${BASE_DIR}/conf-systype"
+fi
+SO_SUFFIX=`head -n 1 "${BASE_DIR}/conf-sosuffix"`
+if [ $? -ne 0 ]
+then
+  fatal "could not read ${BASE_DIR}/conf-sosuffix"
 fi
 
 main="$1"
